{
 "title": "smokepyng",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "s3_type",
    "query": {
     "query": "label_values(s3_request_latency_seconds_sum, type)"
    }
   },
   {
    "name": "vault_type",
    "query": {
     "query": "label_values(vault_request_latency_seconds_sum, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vault_request_latency_seconds_sum{type=~\"$vault_type\"}[$__rate_interval])/rate(vault_request_latency_seconds_count{type=~\"$vault_type\"}[$__rate_interval])\n",
     "legendFormat": "{{name}} - {{type}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "query0" },
  {
   "title": "S3 request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(s3_request_latency_seconds_sum{type=~\"$s3_type\"}[$__rate_interval])/rate(s3_request_latency_seconds_count{type=~\"$s3_type\"}[$__rate_interval])\n",
     "legendFormat": "{{bucket_name}} - {{type}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP request_latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "seconde" } },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[$__rate_interval])/rate(request_latency_seconds_count[$__rate_interval])\n",
     "legendFormat": "{{url_name}}"
    }
   ]
  }
 ]
}